// Service page content. Claims are limited to what is published elsewhere on the site
// (services, price ranges, shipped products). Add proof here only when it is real.

export const PROCESS = [
    { name: 'Discover', text: 'A 30-minute call on your goal, users, budget and timeline. You leave knowing whether we are a fit.' },
    { name: 'Architect', text: 'We choose the stack and system design, and write down scope, risks and a quote before any build starts.' },
    { name: 'Build', text: 'We ship in working increments so you can see and use the product as it grows.' },
    { name: 'Test', text: 'Functional, device and performance testing, plus security review of authentication and data handling.' },
    { name: 'Launch', text: 'Store submission, release configuration, analytics and monitoring, so launch day is not a first run.' },
    { name: 'Improve', text: 'We track what users actually do and keep improving speed, reliability and conversion.' },
];

export const PRICING_NOTE = 'Product and platform builds typically range from $5,000 to $100,000+ depending on scope. Standalone performance audits start at $500. Every project gets a written scope and quote before work starts.';

export const SERVICES = [
    {
        slug: 'mobile-app-development',
        name: 'Mobile App Development',
        icon: 'device',
        blurb: 'Android and iOS apps, designed, engineered and launched end to end.',
        stack: 'Android · iOS · Flutter · React Native',
        title: 'Mobile App Development Company | Mobile1X',
        description: 'Hands-on Android and iOS app development. See our live apps, get transparent pricing and book a 30-minute call.',
        h1: 'Mobile apps, designed, built and launched',
        category: 'Mobile',
        answer: 'Mobile1X designs, builds and launches Android and iOS apps, using native Android, Flutter or React Native depending on what your product needs. We publish our own apps, Notes and Dedup, on Google Play and the App Store, so the team has taken products through store review, updates and real users. Builds typically range from $5,000 to $100,000+ depending on scope.',
        problem: {
            text: 'Most mobile projects that struggle fail for the same few reasons, and almost all of them are decided in the first weeks.',
            points: [
                'The stack was picked for familiarity, not for the product, and becomes a constraint later.',
                'The app worked on the demo device but is slow or unstable on the phones your users own.',
                'Store review, permissions and release configuration were treated as an afterthought.',
                'There is a prototype but no path from prototype to a maintainable product.',
            ],
        },
        solution: 'We start with the product and its users, then choose the platform approach: native Android or iOS for maximum platform capability and performance, or Flutter and React Native when one codebase across both stores is the better trade. You get the reasoning in writing, along with scope, risks and a quote, before the build begins.',
        capabilities: [
            'Android apps and iOS apps, native or cross-platform',
            'Flutter and React Native apps from a single codebase',
            'Backend services and APIs that power the app',
            'Authentication, push notifications, payments and analytics',
            'App store release, updates and post-launch monitoring',
            'Performance, security and modernization of existing apps',
        ],
        tech: [
            { group: 'Native platforms', items: ['Android (Kotlin, Java)', 'iOS (Swift, Objective-C)'] },
            { group: 'Cross-platform', items: ['Flutter', 'React Native'] },
            { group: 'Backend and cloud', items: ['Spring Boot', 'Firebase', 'AWS', 'Cloudflare', 'SQL', 'SQLite'] },
            { group: 'App capabilities', items: ['Authentication', 'Push notifications', 'Payments', 'Offline support', 'Analytics'] },
            { group: 'Delivery', items: ['Store release', 'Crash and performance monitoring', 'Ongoing updates'] },
        ],
        proof: ['notes', 'dedup'],
        faq: [
            { q: 'How much does mobile app development cost?', a: 'Builds with Mobile1X typically range from $5,000 to $100,000+. The main cost drivers are the number of platforms, the number and complexity of features, backend and integration work, and whether the app includes AI or payments. You receive a written scope and quote after a 30-minute discovery call.' },
            { q: 'Should I build native, Flutter or React Native?', a: 'Choose native when you need the deepest platform capability or top performance on one platform. Choose Flutter or React Native when one codebase for Android and iOS matters more. We recommend one after understanding your product, and explain why.' },
            { q: 'Can you take over or modernize an existing app?', a: 'Yes. We begin with a review of the codebase, architecture and store listing, then agree what to fix, refactor or rebuild before quoting the work.' },
            { q: 'Do you publish apps to Google Play and the App Store?', a: 'Yes. Notes is live on Google Play and the App Store and Dedup is live on Google Play, so store submission and review are part of our normal delivery.' },
        ],
        posts: ['native-vs-flutter-vs-react-native', 'how-much-does-it-cost-to-build-a-mobile-app'],
    },
    {
        slug: 'ai-development',
        name: 'AI Development',
        icon: 'spark',
        blurb: 'AI applications, agents and integrations for mobile and web products.',
        stack: 'AI apps · Agents · RAG · On-device AI',
        title: 'AI Development Company: Apps & Agents | Mobile1X',
        description: 'AI applications, agents, RAG and AI integration for mobile and web, built privacy-first. Scoped projects from $5,000. Talk to an engineer.',
        h1: 'AI products that work in production',
        category: 'AI',
        answer: 'Mobile1X builds AI applications, agents, retrieval-augmented generation (RAG) systems and AI integrations for mobile and web products. Our own app Notes is a private, local-first AI notes app live on Google Play and the App Store. AI projects typically start at $5,000 and are scoped after a discovery call.',
        problem: {
            text: 'A demo that answers well is not the same as a feature people can rely on. The gap is usually engineering, not the model.',
            points: [
                'The model has no access to your real data, so answers are generic or wrong.',
                'Sensitive user data is sent to the cloud without a deliberate decision about privacy.',
                'Latency and cost are fine for ten users and unsustainable for ten thousand.',
                'Nobody has defined how to tell whether the AI feature is actually working.',
            ],
        },
        solution: 'We design the AI feature as part of the whole system: where data lives, what runs on the device and what runs in the cloud, how answers are grounded in your content, and how quality is measured. That is what separates an AI feature from an AI demo.',
        capabilities: [
            'AI applications and features inside mobile and web products',
            'AI agents and workflow automation',
            'RAG: answers grounded in your documents and data',
            'AI integration into an existing app or platform',
            'On-device AI versus cloud AI, chosen for privacy, cost and latency',
            'AI chatbots, and lead-scoring and qualification systems for sales teams',
        ],
        tech: [
            { group: 'Patterns', items: ['Agents', 'RAG', 'Chatbots', 'Workflow automation', 'On-device AI'] },
            { group: 'Around the model', items: ['Data pipelines', 'Evaluation', 'Privacy controls', 'Cost and latency monitoring'] },
            { group: 'Product surface', items: ['Android (Kotlin, Java)', 'iOS (Swift, Objective-C)', 'Web (React JS)'] },
        ],
        proof: ['notes'],
        faq: [
            { q: 'Can Mobile1X add AI to an existing mobile app?', a: 'Yes. AI integration into existing products is part of what we do. We start by reviewing your app and the data the feature would use, then scope what is practical, what it costs and how success will be measured.' },
            { q: 'How much does AI development cost?', a: 'AI projects with Mobile1X typically start at $5,000, and larger platforms go to $100,000+. Cost depends on the data involved, the integrations, whether the feature runs on-device or in the cloud, and how much evaluation and hardening it needs.' },
            { q: 'What is RAG and do I need it?', a: 'RAG (retrieval-augmented generation) lets an AI system answer from your own documents and data instead of only its training. You need it when answers must reflect your content, such as support knowledge, product catalogues or internal documents.' },
            { q: 'Do you build privacy-first AI?', a: 'Yes. Our Notes app is local-first with encryption, and we apply the same approach to client work: decide deliberately what data leaves the device, and why.' },
        ],
        posts: ['how-much-does-it-cost-to-build-a-mobile-app'],
    },
    {
        slug: 'mvp-development',
        name: 'MVP Development',
        icon: 'rocket',
        blurb: 'From idea to a launched MVP, with scope and price agreed first.',
        stack: 'Idea → MVP → launch',
        title: 'MVP Development Company: Idea to Launch | Mobile1X',
        description: 'Fixed-scope MVP development for mobile and web. Get a written scope and estimate before we build. Book a 30-minute call.',
        h1: 'Ship your MVP without guessing the cost',
        category: 'MVP',
        answer: 'Mobile1X takes MVPs from idea to launch: we help define the smallest product that tests your idea, then design, build and release it on Android, iOS or the web. You receive a written scope and quote before work starts. MVP and product builds typically range from $5,000 to $100,000+ depending on scope.',
        problem: {
            text: 'An MVP fails in two opposite ways: it is too big to finish, or too thin to learn anything.',
            points: [
                'Scope grows until the launch date and the budget both slip.',
                'Features are built because they were imaginable, not because they test the riskiest assumption.',
                'The first version has no analytics, so launch produces opinions instead of data.',
                'The prototype cannot be extended, so a rebuild is needed as soon as the idea works.',
            ],
        },
        solution: 'We cut scope to the smallest release that answers your main question, agree it in writing, and build on an architecture that can grow if the idea works. Analytics are included from the first release so you learn from real usage.',
        capabilities: [
            'Scope definition: what is in the MVP and what waits',
            'Design and engineering for Android, iOS or web',
            'AI features in the MVP where they are the point of the product',
            'Analytics and feedback loops built in from release one',
            'Store submission and launch support',
            'A foundation that scales beyond the MVP',
        ],
        tech: [
            { group: 'Platforms', items: ['Android (Kotlin, Java)', 'iOS (Swift, Objective-C)', 'Web (React JS)', 'Desktop (ElectronJS)'] },
            { group: 'Backend and cloud', items: ['Spring Boot', 'Firebase', 'AWS', 'Cloudflare', 'SQL', 'SQLite'] },
            { group: 'Included in scope', items: ['Design', 'Backend and APIs', 'Analytics', 'Store release'] },
        ],
        proof: ['notes', 'dedup'],
        faq: [
            { q: 'How much does MVP development cost?', a: 'MVP builds with Mobile1X typically range from $5,000 to $100,000+ depending on platforms, features and integrations. You get a written scope and quote before work starts.' },
            { q: 'How long does an MVP take?', a: 'It depends on scope, so we do not quote a generic timeline. After a 30-minute discovery call you receive a scoped estimate that includes timing.' },
            { q: 'Should I build the MVP in-house or outsource it?', a: 'Build in-house when you already have the engineers and product leadership, and speed to first release is not critical. Outsource when you need a working team quickly or want to avoid hiring before the idea is validated. Either way, keep ownership of your code and product decisions.' },
            { q: 'What happens after the MVP launches?', a: 'We can keep improving the product from real usage data, hand it to your own team, or both. The code and architecture are built to be handed over.' },
        ],
        posts: ['how-much-does-it-cost-to-build-a-mobile-app', 'native-vs-flutter-vs-react-native'],
    },
    {
        slug: 'fintech-development',
        name: 'Fintech Engineering',
        icon: 'bank',
        blurb: 'Payments, banking integrations and security-conscious architecture.',
        stack: 'Payments · Banking APIs · Security',
        title: 'Fintech Software Development | Mobile1X',
        description: 'Fintech engineering: payment and banking API integrations with security-conscious, compliance-minded architecture. Talk to an engineer.',
        h1: 'Fintech engineering, security first',
        category: 'Fintech',
        answer: 'Mobile1X engineers fintech platforms for banks, startups and enterprises, including payment and banking API integrations and security-conscious architecture designed to support compliance work. Fintech builds typically range from $5,000 to $100,000+ depending on scope.',
        problem: {
            text: 'In financial software the expensive mistakes are quiet ones: a retry that double-charges, a log that leaks, a permission that is too wide.',
            points: [
                'Integrations with banks and payment providers fail in ways the happy path never shows.',
                'Security is added at the end and becomes a rewrite.',
                'Audit and compliance needs are discovered after the architecture is fixed.',
                'Money-handling code is not designed to be reconciled or explained.',
            ],
        },
        solution: 'We design for failure first: idempotent operations, clear transaction states, least-privilege access and audit-friendly logging, built into the architecture from the start. Compliance is a property of your organisation and regulator, so we build systems that make compliance work easier and work with your security and compliance stakeholders.',
        capabilities: [
            'Payment provider and banking API integrations',
            'Secure authentication, authorization and data protection',
            'Transaction flows designed for retries, failure and reconciliation',
            'Compliance-minded architecture: audit trails, access control, data handling',
            'Mobile and web front ends for financial products',
            'Security review of existing fintech systems',
        ],
        tech: [
            { group: 'Integrations', items: ['Payment gateways', 'Banking APIs', 'Webhooks'] },
            { group: 'Security', items: ['Authentication', 'Access control', 'Encryption', 'Audit logging'] },
            { group: 'Backend', items: ['Spring Boot', 'SQL', 'AWS', 'Cloudflare'] },
            { group: 'Product surface', items: ['Android (Kotlin, Java)', 'iOS (Swift, Objective-C)', 'Web (React JS)'] },
        ],
        proof: ['pos', 'a2z', 'pharma'],
        proofNote: 'We do not yet have a public fintech case study. Related shipped work involving billing, checkout and ordering is below, and we are glad to discuss relevant experience on a call.',
        faq: [
            { q: 'Does Mobile1X build fintech platforms?', a: 'Yes. We engineer secure, scalable fintech systems for banks, startups and enterprises, including banking and payment API integrations.' },
            { q: 'Do you guarantee PCI DSS or regulatory compliance?', a: 'No. Compliance depends on your organisation, your regulator and how the whole system is operated. We build compliance-minded architecture and work with your security and compliance stakeholders to support it.' },
            { q: 'How much does a fintech build cost?', a: 'Fintech builds typically range from $5,000 to $100,000+ depending on integrations, security requirements and platforms. You receive a written scope and quote after a discovery call.' },
        ],
        posts: [],
    },
];

export const serviceBySlug = Object.fromEntries(SERVICES.map((s) => [s.slug, s]));
